### PR TITLE
update logo; add logo to README

### PR DESCRIPTION
**Pull request by cvan**
and crushed the PNG

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @cvan, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by mattbasta** [comment]
Thanks for the pull, man. I'll get this file in separately. I would ultimately like to get the file into the docs branch script so it gets hosted on gh-pages. Or maybe I'll see if I can get the PSD converted to SVG and do it inline. Who knows. I'll experiment :)

**Comment by mattbasta** [comment]
I'm going to close this since it's not merge-able anymore. Feel free to re-submit after rebasing and signing the Box CLA! :+1:

**Comment by cvan** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @cvan has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by cvan** [comment]
rr? @mattbasta

**Comment by mattbasta** [comment]
Much appreciated!

**Pull request merged**
