### PR TITLE
Add proper file existence check for compiled template files

### PR DESCRIPTION
**Pull request by vctrshn**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @vshen94, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by vctrshn** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @vshen94 has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by mattbasta** [comment]
Perfect, thanks

**Pull request merged**
